# Generated by Django 4.2.11 on 2024-03-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
